# Generated by Django 6.0.4 on 2026-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='complaints',
            field=models.TextField(blank=True, help_text='Current symptoms and complaints', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnostic_referrals',
            field=models.TextField(blank=True, help_text='Referrals for CT, MRI, X-Ray, blood tests, or other specialists', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='history_of_disease',
            field=models.TextField(blank=True, help_text='Anamnesis morbi (how long it lasts, previous treatments)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='history_of_life',
            field=models.TextField(blank=True, help_text='Anamnesis vitae (allergies, chronic diseases)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='preliminary_diagnosis',
            field=models.CharField(blank=True, help_text='Preliminary or final diagnosis', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.TextField(blank=True, help_text='General recommendations (diet, lifestyle, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True, help_text='Medications prescribed by the doctor', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Medical ID / Clinic License'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('CLINIC', 'Clinic')], default='PATIENT', max_length=20, verbose_name='Role'),
        ),
    ]
